name: Go

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "*/go.sum"
      - "*/go.mod"
      - "**/*.go"
      - "*/.golangci.yml"
      - "*/Makefile"

env:
  GOLANGCI_LINT_VERSION: v2.2.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go_src/go.mod

      - name: Build
        run: (cd go_src/ && make build)

  lint-internal:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go_src/go.mod

      - name: Run golangci-lint in internal
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=10m ./internal/...
          working-directory: go_src

  lint-cmd:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go_src/go.mod

      - name: Run golangci-lint in cmd
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=10m ./cmd/...
          working-directory: go_src

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go_src/go.mod

      - name: Run tests
        run: (cd go_src/ && make test)
